import { DocItem, Category } from './types';

export const APP_CONFIG = {
  PASSWORD: '2693988',
};

export const REGULATION_CATEGORIES: Category[] = [
  { id: 'org', name: '組織系列' },
  { id: 'tech', name: '技術系列' },
  { id: 'finance', name: '財務系列' },
  { id: 'marketing', name: '行銷系列' },
  { id: 'integrity', name: '品格系列' },
];

export const FLOWCHART_CATEGORIES: Category[] = [
  { id: 'dept1', name: '一部門' },
  { id: 'dept2', name: '二部門' },
  { id: 'dept3', name: '三部門' },
  { id: 'dept4', name: '四部門' },
  { id: 'dept5', name: '五部門' },
  { id: 'dept6', name: '六部門' },
  { id: 'dept7', name: '七部門' },
];

export const FORM_CATEGORIES: Category[] = [
  { id: 'docs', name: '文書檔案' },
  { id: 'seals', name: '印鑑相關' },
  { id: 'finance_form', name: '財務相關' },
  { id: 'hr', name: '人事相關' },
  { id: 'pr', name: '公關相關' },
  { id: 'mgmt', name: '管理相關' },
  { id: 'profit', name: '穩盈相關' },
];

export const REGULATIONS_DATA: DocItem[] = [
  { id: 'reg_org_0', title: '0. 工作規則', date: '2023/12/07', url: 'https://drive.google.com/file/d/162Ypn3-kp7ENhSdJ2KByYrH3zWxyPCdl/preview', description: '規範勞資雙方權利義務。', category: 'org' },
  { id: 'reg_org_1', title: '1. 目標與目的規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1eTqS3bMABIexMjFmjighRF-932K-iwYtxGCuxTqi7SA/preview', description: '明確定義公司的短期目標與長期願景。', category: 'org' },
  { id: 'reg_org_2', title: '2. 公司歷史規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1sqckdA0LorOmgAPLTPVcd5IX9glpY6JrCnDpLE011BU/preview', description: '記錄公司發展歷程。', category: 'org' },
  { id: 'reg_org_3', title: '3. 最終有價值產品規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1LkRpu50VcovwOldcXcVf62ZjN-Vc0ghpha82SM2XSx8/preview', description: '定義公司各職位最終應交付的有價值產品。', category: 'org' },
  { id: 'reg_org_4', title: '4. 組織圖使用規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1Uo1MSRM_Wk60sPmbzSRisHozcB5aEYn6y0C3sE4XmdY/preview', description: '闡述組織架構圖之閱讀方式。', category: 'org' },
  { id: 'reg_org_5', title: '5. 各課的職責', date: '2025/02/01', url: 'https://docs.google.com/document/d/1ku0Ej2LLShAs8LZzGINfrTEOmOVT2U422_cU4DoYAsQ/preview', description: '詳細列出各課級單位的職掌範圍。', category: 'org' },
  { id: 'reg_org_6', title: '6. 每週職員會議規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1ohWmuWllovNUWZ-n_q9jOXY2-cUC-ACAUQJ8sEyCXZQ/preview', description: '規範每週例會的進行流程。', category: 'org' },
  { id: 'reg_org_7', title: '7. 書面溝通規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1iaUQH5ld4MwWAbUg7Cnaw9EXpm6yCSTqj-T9XUUzpX0/preview', description: '定義內部文書往來的格式。', category: 'org' },
  { id: 'reg_org_8', title: '8. 命令規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1Tc1y9xmOER4fa6lJ0JR5YHlGpYI13RDrb585Xi4Mg5w/preview', description: '闡述上級下達命令的標準程序。', category: 'org' },
  { id: 'reg_org_9', title: '9. CSW規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1lU7gyS4a1zoKhOJA4_WUqelVHQ0pr2fiFUdxGPuLrI8/preview', description: '完成職員工作（CSW）的標準定義。', category: 'org' },
  { id: 'reg_org_10', title: '10. 工作資料夾規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1LL5FQQwiqjJf8MaXXUwUPBhqEmDSmhfKm95CcyEpDPI/preview', description: '規範個人工作資料的分類與歸檔。', category: 'org' },
  { id: 'reg_org_11', title: '11. 工作資料夾檢視規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1Z-A26U00KEfRUfp2pGWUmHVkU1N_lElXT3yCT790jZw/preview', description: '主管定期檢視工作資料夾的標準。', category: 'org' },
  { id: 'reg_org_12', title: '12. 如何撰寫規章的規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1c3sAQv1uzgKfm3w3jPlLBdlzXlOfv3SIBVPxLRursIo/preview', description: '制定公司內部規章文件的標準格式。', category: 'org' },
  { id: 'reg_org_13', title: '13. 統計曲線規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1qNhw6b_9OM3q-HSjuZbNsK6svpiwFMRRyd0TGsNTfEU/preview', description: '說明如何繪製與解讀績效統計曲線。', category: 'org' },
  { id: 'reg_org_14', title: '14. 職員出勤規章', date: '2025/02/06', url: 'https://docs.google.com/document/d/17wdy8YJ-IeBDUjsmLi0pSYYF572BPvH3_WRaHUL3ctM/preview', description: '規定打卡、遲到早退、加班與休假。', category: 'org' },
  { id: 'reg_org_15', title: '15. 如何修改公司管理工具規章', date: '2025/01/20', url: 'https://docs.google.com/document/d/1nzs_RmDkEtFRlzozNbHthElDOJTH1H9ulqD33Gtj54g/preview', description: '定義管理系統的變更流程。', category: 'org' },
  { id: 'reg_org_16', title: '16. 辦公室用品操作與管理規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1INOPF34RMO_gUh5gegOBNSwK101r9Z78e17Er8E7T9Y/preview', description: '規範辦公設備與耗材的管理規則。', category: 'org' },
  { id: 'reg_org_17', title: '17. 印鑑與負責人簽名管理規章', date: '2024/06/14', url: 'https://docs.google.com/document/d/1R7dp1eWYWbbhM4SoHly1dZPdHs0pShHL3OWjMVGcuRI/preview', description: '控管公司大小章及簽名使用權限。', category: 'org' },
  { id: 'reg_org_18', title: '18. 協調手冊', date: '2024/04/18', url: 'https://docs.google.com/document/d/1NfBiBdyS7Pf4mlhbsYuZrleas88Ga_t-Sbw4OVfyT8E/preview', description: '跨部門溝通與衝突解決原則。', category: 'org' },
  { id: 'reg_org_19', title: '19. 如何移轉職責', date: '2024/04/22', url: 'https://docs.google.com/document/d/11iA-peENwzDCVinKlT_FMuEjD6hzpjyY9qPAY9XTNtw/preview', description: '職務交接與職責移轉確認流程。', category: 'org' },
  { id: 'reg_org_20', title: '20. 如何開始在新職位上運作', date: '2024/04/22', url: 'https://docs.google.com/document/d/10Yc-fZfdW_CtTuARuPov0NVvM95YNSTDZ_eVfuYb3-o/preview', description: '新進或異動人員的快速上手指南。', category: 'org' },
  { id: 'reg_org_21', title: '21. 企業主10年戰略方針', date: '2024/08/21', url: 'https://docs.google.com/document/d/1FkCVnLRd0mhCGDsbFaEvoyVZXSDn7NzXwCBhvw7Miss/preview', description: '企業未來發展藍圖與戰略目標。', category: 'org' },
  { id: 'reg_org_22', title: '22. 管理等級表(2025年版)', date: '2024/08/21', url: 'https://docs.google.com/document/d/1_IRQ1fhBttZnYvCnnwtXELGCFAaOYhKrVQFhxdewc3I/preview', description: '公司內部管理職級體系表。', category: 'org' },
  { id: 'reg_org_23', title: '23. 個人職務說明培訓', date: '2024/04/22', url: 'https://docs.google.com/document/d/1JmFMkUXkYe2k3SRL0tNG_IbBl5KtwOr-IJZy48-q7RA/preview', description: '職務說明書內容的教育訓練。', category: 'org' },
  { id: 'reg_org_24', title: '24. 主管的責任', date: '2024/04/22', url: 'https://docs.google.com/document/d/1eQbbZOSe61-zxRrsyPoUQU9ygNIQX6EgOtcADgSOM4A/preview', description: '各級主管的領導與績效責任。', category: 'org' },
  { id: 'reg_org_25', title: '25. 腦力激盪', date: '2024/05/02', url: 'https://docs.google.com/document/d/1zDHVImzFwPgxILJje9qjSQFZu5OiQ_WtHlWNFOuQ0PM/preview', description: '創意發想會議進行方式。', category: 'org' },
  { id: 'reg_org_26', title: '26. 應付與組織規章', date: '2024/05/13', url: 'https://docs.google.com/document/d/1Ec6bN0ePj2iLtJNicWaimW71AeynIfgT7REUyV5bzJw/preview', description: '組織突發狀況或危機的應變機制。', category: 'org' },
  { id: 'reg_org_27', title: '27. 年度計畫規章', date: '2025/01/06', url: 'https://docs.google.com/document/d/1LSoCk9inoTTUC4BA-yXCss6HiU9mXwapfAOXkzi-0Gg/preview', description: '年度營運計畫制定與執行。', category: 'org' },
  { id: 'reg_org_28', title: '28. 集團行事曆規章', date: '2024/11/14', url: 'https://docs.google.com/document/d/1VC2NhVz4pfi0dMLiIxrIWkhx2iWLH7BReCfDRoY2xto/preview', description: '集團重要活動與行事曆管理。', category: 'org' },
  { id: 'reg_org_29', title: '29. 職員終止契約與職務移轉規章', date: '2025/03/06', url: 'https://docs.google.com/document/d/1O43I83txCawPkKjiD0nOecEbSgrGWtnmoucxmnFq6nM/preview', description: '離職契約終止與工作交接。', category: 'org' },
  { id: 'reg_org_30', title: '30. 職務說明_公版', date: '2024/07/15', url: 'https://docs.google.com/document/d/13y4I-WmtBJZM7Gf2-5Uds0LqfwQYP16n/preview', description: '標準化職務說明書範本。', category: 'org' },
  { id: 'reg_org_31', title: '31. 職務職責與運行規章', date: '2024/11/14', url: 'https://docs.google.com/document/d/11KSGIeCLfk97jXwmP09DMkhhl0z2O9fwxBoTtjmj54s/preview', description: '職務職責履行與日常運行準則。', category: 'org' },
  { id: 'reg_org_32', title: '32. 出差費用管理辦法規章', date: '2024/08/15', url: 'https://docs.google.com/document/d/1DiCgOu38eg1RpdBXQjUY2qr6RcWn9Uw0ZJesmVnzWCQ/preview', description: '國內外出差費用報支標準。', category: 'org' },
  { id: 'reg_org_33', title: '33. 職務移轉規章附件', date: '2024/07/15', url: 'https://docs.google.com/document/d/1-yTTqGmEaMeq_hVA5wvtuCKfa5hj6cYiBLB-FpGytjA/preview', description: '職務移轉附件表格。', category: 'org' },
  { id: 'reg_org_34', title: '34. 職務移轉規章', date: '2024/07/15', url: 'https://docs.google.com/document/d/11iA-peENwzDCVinKlT_FMuEjD6hzpjyY9qPAY9XTNtw/preview', description: '職務移轉標準作業流程。', category: 'org' },
  { id: 'reg_org_35', title: '35. 投資客戶資料管理規則', date: '2025/02/06', url: 'https://docs.google.com/document/d/13NNiO_cmzUF2T3egu8phmUijc-lFKASpeNjv-4pjobg/preview', description: '投資客戶個資保護與管理。', category: 'org' },
  { id: 'reg_org_36', title: '36. 戰略與戰術會議規章', date: '2025/02/06', url: 'https://docs.google.com/document/d/1wMquAiR4Sso1svSW4yub_Bw1XjaZXe47JubtgdjrtgM/preview', description: '會議運作模式定義。', category: 'org' },
  { id: 'reg_org_37', title: '37. 企業文件審核規範', date: '2025/02/27', url: 'https://docs.google.com/document/d/14rlMJ89loSK-S_wFWkkKkM_xXc2TRKETlzKNDnohRew/preview', description: '文件發布審核機制。', category: 'org' },
  { id: 'reg_org_38', title: '38. 簽約獎金政策規章', date: '2025/03/27', url: 'https://docs.google.com/document/d/18D1Dp3E3zfajABxt8SenCrOY_in4ZWBziJQLU2mwbPs/preview', description: '獎金計算與發放條件。', category: 'org' },
  { id: 'reg_org_39', title: '39. 專案管理規章', date: '2025/03/27', url: 'https://docs.google.com/document/d/1eSRecDt0eCfGVVz0ggKvq35KBXEOsNRHmuFahvH9RXg/preview', description: '專案全生命週期管理。', category: 'org' },
  { id: 'reg_org_40', title: '40. 合約規章', date: '2026/01/15', url: 'https://docs.google.com/document/d/1GNgY8kTjzZ4VQoVu6Nblo2luo9z3iZfYr9znVGpX1mg/preview', description: '合約擬定與審閱規範。', category: 'org' },
  { id: 'reg_org_41', title: '41. 年度目標展開與執行流程規章', date: '2025/04/18', url: 'https://docs.google.com/document/d/1zwgQyS4rba3aayyNZ8XQvM2wUQa6z1csKlTcozGi_bM/preview', description: '年度目標KPI拆解流程。', category: 'org' },
  { id: 'reg_org_42', title: '42. 人力招募與任用', date: '2025/05/23', url: 'https://docs.google.com/document/d/13aSUbNn7gz1E-Gcn0Mlp5Tt8uTd6ukdWCXaZPNhE54E/preview', description: '人才甄選任用程序。', category: 'org' },
  { id: 'reg_org_43', title: '43. 職員內部公關', date: '2025/06/13', url: 'https://docs.google.com/document/d/1vIk5lgpCBvVqkjR299-uq0mglQ4L_JFMVb8B96p1ljc/preview', description: '內部溝通與關係維護。', category: 'org' },
  { id: 'reg_org_44', title: '44. 感謝小卡', date: '2025/06/13', url: 'https://docs.google.com/forms/d/e/1FAIpQLSeZvkR5M8M31ryjYwSzj5f3tRnNFf17GVcmsqHo0VTDtufc2w/viewform', description: '內部感恩文化推動。', category: 'org' },
  { id: 'reg_org_45', title: '45. 穩盈策略顧問股份有限公司_行政管理等級表', date: '2025/06/13', url: 'https://docs.google.com/document/d/14ekkF3a2lNY5VGtdep5u6v4-usQ-lkeePc4txia_nHY/preview', description: '行政職級與權限表。', category: 'org' },
  { id: 'reg_org_46', title: '46. 企業宣傳與教育發布規範', date: '2025/06/20', url: 'https://docs.google.com/document/d/1lBqwNgG_fX2mlANTlYeDgITpHOxWD8sVgv43t979nWk/preview', description: '對外宣傳與教材發布標準。', category: 'org' },
  { id: 'reg_org_47', title: '47. 職災處理辦法', date: '2025/06/20', url: 'https://docs.google.com/document/d/1vFL9JKH89MYZxtRJl7wOz88-I-Mna1-30y6inRJ9FIo/preview', description: '職業災害通報與處理。', category: 'org' },
  { id: 'reg_org_48', title: '48. 文書檔案管理', date: '2025/06/20', url: 'https://docs.google.com/document/d/1Wq7q3OQp-0LqPYOFmoUvmct5vyMiY2qd/preview', description: '文件編碼與歸檔規則。', category: 'org' },
  { id: 'reg_org_49', title: '49. 文件審查規章', date: '2025/07/16', url: 'https://docs.google.com/document/d/13BVLST5ywds1CTy91HU2498WJ2D1j9NRipKS2pJysRs/preview', description: '發行文件之審查機制。', category: 'org' },
  { id: 'reg_org_51', title: '51. 會議規章', date: '2025/07/31', url: 'https://docs.google.com/document/d/1lr1oE7VFL8Csr5bWv00aC_-aPI-e9UWYz3PuGhIFJOI/preview', description: '會議召集與紀錄規範。', category: 'org' },
  { id: 'reg_org_52', title: '52. 流程圖製作與審核', date: '2025/09/05', url: 'https://docs.google.com/document/d/1zSHcN0Ticx7o375NBkU3M4bdYqv9wA2ge5jn8BSKWWU/preview', description: 'SOP流程圖繪製標準。', category: 'org' },
  { id: 'reg_org_53', title: '53. 法律案件責任與協作管理', date: '2025/11/13', url: 'https://docs.google.com/document/d/11oKV6mLijdVG5L9cNJdi0wmhce3MKhLp49s5DB05XOQ/preview', description: '訴訟案件處理權責。', category: 'org' },
  { id: 'reg_org_54', title: '54. 獎金與激勵辦法', date: '2025/11/20', url: 'https://docs.google.com/document/d/1LaZNZfvdwmx3SJicbm8l22j-UHfGJPG7pZzUeEcgVz0/preview', description: '績效獎金核發標準。', category: 'org' },
  { id: 'reg_org_55', title: '55. 績效管理與考核辦法', date: '2025/11/07', url: 'https://docs.google.com/document/d/1o8f_penur56ymLaKpJke3cYBGrcjqxB6KDjFSI7q8NE/preview', description: '績效考核制度。', category: 'org' },
  { id: 'reg_org_56', title: '56. 薪酬結構辦法', date: '2025/11/07', url: 'https://docs.google.com/document/d/1qJfjUte_VEVqwMjIYi1vA9Lm_8sRYOD34zBiwpaRUgg/preview', description: '薪資組成原則。', category: 'org' },
  { id: 'reg_org_57', title: '57. 職員培訓辦法', date: '2025/11/14', url: 'https://docs.google.com/document/d/1I-RB7rBn99vvmQMNyh9BVevA13UW3po4LMU6iGZ5Wno/preview', description: '培訓申請與公假規範。', category: 'org' },
  { id: 'reg_org_58', title: '58. 職員發展與晉升辦法', date: '2025/11/14', url: 'https://docs.google.com/document/d/1NnMTD1e8xLOemtLwQzqVJhkHIm1FX9dvnBPChEGfHAo/preview', description: '職涯發展與晉升條件。', category: 'org' },
  { id: 'reg_org_59', title: '59. 商務衝突與人員安全防護管理辦法', date: '2026/01/22', url: 'https://docs.google.com/document/d/1ndW7o_SL5jDa2r2l7vzLgoRwnxbOmWy6H53ATZtJV1M/preview', description: '規範商務活動中潛在衝突的預防機制與人員安全防護措施。', category: 'org' },
  { id: 'reg_org_60', title: '60. 帳號管理規章', date: '2025/03/03', url: 'https://docs.google.com/document/d/1UWPkkwxgpC45yNa6zgAW8kDEZNzCt_g-VdUpxOLyJAE/preview', description: '規範帳號申請、權限管理與停用流程。', category: 'org' },
  { id: 'reg_tech_1', title: '1. 公佈欄發布規章', date: '2024/12/05', url: 'https://docs.google.com/document/d/1-xUgpXYp5hVb4IYzvmq4KJtxyOwa9Z00YBytMvqPi54/preview', description: '規範公司實體與數位公佈欄的資訊張貼。', category: 'tech' },
  { id: 'reg_tech_2', title: '2. 應收帳款分期客戶合約到期展期', date: '2024/07/03', url: 'https://docs.google.com/document/d/1Ksv32RKYyyloO12G1adtfgZ7A3WQTTNzc_olZAXExLs/preview', description: '客戶分期合約到期後的續約評估。', category: 'tech' },
  { id: 'reg_tech_3', title: '3. 帳務系統操作手冊', date: '2024/09/02', url: 'https://docs.google.com/document/d/1xMCeaP-ayd9O6AGueHyTMRS0bbJGvPGLZmz4JNoJslI/preview', description: '內部帳務管理系統操作指南。', category: 'tech' },
  { id: 'reg_tech_4', title: '4. 不動產鑑價作業規章', date: '2024/12/17', url: 'https://docs.google.com/document/d/1_82d8VjrequcHkIJKNryNNBlOTBYp7Cs9O3ReyChSPU/preview', description: '不動產價值評估流程。', category: 'tech' },
  { id: 'reg_tech_5', title: '5. 財富奧秘之旅玩家指南規章', date: '2024/11/14', url: 'https://docs.google.com/document/d/15S_ZiwellhyuMvi_6ZqkU9UIhjHYvx_beaeY_5P4fj8/preview', description: '財富遊戲化教育訓練規則。', category: 'tech' },
  { id: 'reg_tech_6', title: '6. 銀行金鑰管理規章', date: '2024/05/20', url: 'https://docs.google.com/document/d/1meaTo3hZrCpbVr3utXUu_2G_WI-fAYElqq2HaYv2AKE/preview', description: '網銀憑證保管與權限控管。', category: 'tech' },
  { id: 'reg_tech_7', title: '7. 客戶借款違約金減免規範', date: '2026/01/15', url: 'https://docs.google.com/document/d/1sENv03QyGSyUQ33ZideG2gqfgJNnkYKEFKxUKO0Gxtk/preview', description: '違約金減免審核標準。', category: 'tech' },
  { id: 'reg_tech_8', title: '8. 案件授信準則', date: '2026/01/15', url: 'https://docs.google.com/document/d/1XBWiowUJJcEzECwgKDV3E0kxZ8rZO7Qphd2EG5hBKqE/preview', description: '風險評估與核貸條件。', category: 'tech' },
  { id: 'reg_tech_9', title: '9. 案件催收壓力等級表', date: '2024/03/20', url: 'https://docs.google.com/document/d/1SMH-AgOZAKoTICJj9OF-j6mPeLBx67lJ/preview', description: '逾期案件分類與催收強度。', category: 'tech' },
  { id: 'reg_tech_10', title: '10. 個案合約審核及管理辦法', date: '2025/07/11', url: 'https://docs.google.com/document/d/1LKFe8k9ykFYdW-FKa1cNt2faqG8zczUrOFuNf7EOgZg/preview', description: '特殊合約法務審核流程。', category: 'tech' },
  { id: 'reg_tech_11', title: '11. 不動產擔保提供報酬規範', date: '2025/07/11', url: 'https://docs.google.com/document/d/1TB7iIazCdSpNTQ9xlbU9l4Owa1uYy0R9ZVL9m8aP52k/preview', description: '擔保品報酬計算與支付。', category: 'tech' },
  { id: 'reg_tech_12', title: '12. 案件移轉辦法', date: '2025/07/16', url: 'https://docs.google.com/document/d/1ZIQ6u0c8melyW2qfIcfQjhNtrHr7RjCqcoBfOoij3HI/preview', description: '案件權益移轉程序。', category: 'tech' },
  { id: 'reg_tech_13', title: '13. 投資人會員分級規章', date: '2025/07/31', url: 'https://docs.google.com/document/d/1SinDUT_rduYlov2kbs32mhf3V6H-Ra1VcPgvRov1rkE/preview', description: '投資人分級與服務差異。', category: 'tech' },
  { id: 'reg_tech_14', title: '14. 投資人投資流程規章', date: '2025/08/14', url: 'https://docs.google.com/document/d/1Mwde1iuceOSp-vRpXuGN5Sz8TwgbQ5rLJLEexVMSf8Y/preview', description: '投資標準作業程序。', category: 'tech' },
  { id: 'reg_tech_15', title: '15. 投資人退資流程規章', date: '2025/08/14', url: 'https://docs.google.com/document/d/1XuOBsViU9XRXkdrWlZm7P9QDu2fY_DxD1brEmnJL5cg/preview', description: '退資申請與結算撥款。', category: 'tech' },
  { id: 'reg_tech_16', title: '16. 投資通路管理規範', date: '2025/09/05', url: 'https://docs.google.com/document/d/1Es4kjY_Ka3feA-3Um3WeHkTLtn0AqoqoQ-drOkArrII/preview', description: '資金渠道合作與佣金制度。', category: 'tech' },
  { id: 'reg_tech_17', title: '17. 客戶逾期支付利息管理與減免辦法', date: '2025/10/17', url: 'https://docs.google.com/document/d/1v-PUTO8GOL4Xnca8bY2bGkPZU5ezo4Dd7N-1SWF9l2Q/preview', description: '逾期利息計算與減免申請。', category: 'tech' },
  { id: 'reg_tech_18', title: '18. 募資業務獎金分潤規範', date: '2025/03/03', url: 'https://docs.google.com/document/d/1uXMmbKBBoABEJ47d0X2hzdLtS6ScuUbglD0U36a-SqI/preview', description: '規範募資業務之獎金計算與分潤機制。', category: 'tech' },
  { id: 'reg_fin_1', title: '1. 財務計畫3.0規章', date: '2025/02/06', url: 'https://docs.google.com/document/d/1d1Y96RYF7BVznr67jlPZeK-G7l0NoLJCmJzS48js-uU/preview', description: '財務規劃與預算執行準則。', category: 'finance' },
  { id: 'reg_fin_2', title: '2. 集團內部借貸規則', date: '2024/12/25', url: 'https://docs.google.com/document/d/1Y4Z7HRLAmPXZst3Bzt3ZFLpgszUcUqFQJyBoN9c_fNE/preview', description: '子公司間資金調度程序。', category: 'finance' },
  { id: 'reg_fin_3', title: '3. 借款案件報價與獎勵規章', date: '2025/02/27', url: 'https://docs.google.com/document/d/1ZvVhP_00-W_KpbqmSRcZybi7TMb49YpFAHB7aPK4KnA/preview', description: '利率定價與業務獎勵。', category: 'finance' },
  { id: 'reg_fin_5', title: '5. 稅務計畫', date: '2025/03/03', url: 'https://docs.google.com/document/d/1LJcLSJzwS1s79z6gkZgWftZjVMKzBZcrAoM6mGC1QJQ/preview', description: '公司稅務申報與規劃原則。', category: 'finance' },
  { id: 'reg_fin_6', title: '6. 帳務計畫', date: '2025/03/03', url: 'https://docs.google.com/document/d/1SQrsNpjLHLD0RPP3CWc7kgeubGM_X-pn5XOlcYS_Agg/preview', description: '公司帳務處理與核銷計畫。', category: 'finance' },
  { id: 'reg_mkt_1', title: '1. 行銷外包規定', date: '2025/02/06', url: 'https://docs.google.com/document/d/1HanQAEhbq2AwcUQ6si-zVPObSR00Hgxf-8vQGmJC8wA/preview', description: '行銷專案委外與成效評估。', category: 'marketing' },
  { id: 'reg_int_1', title: '1. 示知報告規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1DQwl2vBspWVvss4bI_8jblDjPAm9-C7s4T9jGPgdteE/preview', description: '異常狀況通報程序。', category: 'integrity' },
  { id: 'reg_int_2', title: '2. 品格梯度階層規章', date: '2025/02/01', url: 'https://docs.google.com/document/d/1fdNprYV3AAqPJ5Lb-DgroRNose8N1vzOpoT1tqXbUMg/preview', description: '品格道德標準與行為準則。', category: 'integrity' },
  { id: 'reg_int_3', title: '3. 狀況公式', date: '2024/04/18', url: 'https://docs.google.com/document/d/1n3NZnFDRYbCKX2HdfmFNzyDXt0uiSi2OUnE9iaBjAN4/preview', description: '處境判斷與應對公式。', category: 'integrity' },
  { id: 'reg_int_4', title: '4. 如何清字', date: '2024/04/22', url: 'https://docs.google.com/document/d/1l_y605Cbgb5ov2dR660sHLWi4TMrZK7QuprJqMeqHyk/preview', description: '學習技術與字詞釐清。', category: 'integrity' },
  { id: 'reg_int_5', title: '5. 多事資料', date: '2024/12/26', url: 'https://docs.google.com/document/d/10Nt-wP8WNBX80ZcLmna7eodAo5J9p-0V97Jvg4wJgZw/preview', description: '識別內部潛在麻煩來源。', category: 'integrity' },
  { id: 'reg_int_6', title: '6. 阻止口頭技術規章', date: '2024/06/27', url: 'https://docs.google.com/document/d/1GjFhHPYZcbLptKCphDnFzevhC5n0tTmuZU6bYrdPS04/preview', description: '落實書面溝通文化。', category: 'integrity' },
  { id: 'reg_int_7', title: '7. 生存與動機', date: '2024/09/05', url: 'https://docs.google.com/document/d/1_krjuq4XBAViuTjQM55EgW51TwJ0bks06uyBu6lvg3Q/preview', description: '激發正向工作動力。', category: 'integrity' },
  { id: 'reg_int_8', title: '8. 快速流動行動週期與品格', date: '2024/09/05', url: 'https://docs.google.com/document/d/1S5dxCdUybg45vQMCQ6t5QJn0xCbH98dwPdnu6Grc8iY/preview', description: '高效率執行與品格結合。', category: 'integrity' },
  { id: 'reg_int_9', title: '9. 辦公室戀愛管理規章', date: '2024/12/04', url: 'https://docs.google.com/document/d/1T6yOfQ3vPctMfPnPXr7vr0B1wQOiYOY5czlbEO48KQ8/preview', description: '辦公室戀情申報與規範。', category: 'integrity' },
  { id: 'reg_int_10', title: '10. 檢視職員的必要性', date: '2025/06/13', url: 'https://docs.google.com/document/d/1FEuce0ZZtDbDjs9LdDljIzl1p8RT1Qtcqfx9lVAEgmQ/preview', description: '職位價值與適任性評估。', category: 'integrity' },
  { id: 'reg_int_11', title: '11. 融資經營品格政策', date: '2026/01/15', url: 'https://docs.google.com/document/d/1s2fhoKvgU2fxt7hkKaNjuuhPHf76ixVovWsgrnRCQQQ/preview', description: '定義融資業務經營過程中的道德標準與品格政策。', category: 'integrity' },
];

export const FLOWCHARTS_DATA: DocItem[] = [
  { id: 'flow_d1_3', title: '出差申請粒子流程表', date: '2024/09/05', url: 'https://docs.google.com/document/d/1TO1GRS2AiGpBUAlfqA02v4I5xfMln3Z7ZACk07ef1II/preview', description: '員工出差申請標準流程。', category: 'dept1' },
  { id: 'flow_d1_4', title: '離職流程表(自請離職版)', date: '2024/09/05', url: 'https://docs.google.com/document/d/1yKxLUiTrSKajfDJi4ThT_bUHPiE3T7JRfAkToR8hmus/preview', description: '員工自願離職程序。', category: 'dept1' },
  { id: 'flow_d1_5', title: '離職流程表(非自願離職版)', date: '2024/09/05', url: 'https://docs.google.com/document/d/1pVVU7deYNCG1d34O1fVi8Qj5bWb5m0XbK3tV9yf_bkE/preview', description: '非自願離職處理程序。', category: 'dept1' },
  { id: 'flow_d1_6', title: '加速員30天挑戰賽流程表', date: '2025/09/22', url: 'https://docs.google.com/document/d/13tt2ByyQUgaCpuXp2yEFXEbtE0s70AWg/preview', description: '新進人員首月挑戰任務。', category: 'dept1' },
  { id: 'flow_d1_1', title: '薪資發放粒子流程表', date: '2024/10/23', url: 'https://docs.google.com/document/d/1debhkhgq-GItRL5_73hLP184O41lrvPQijXTXL5akaU/preview', description: '每月薪資結算流程。', category: 'dept1' },
  { id: 'flow_d1_2', title: '請假粒子流程表', date: '2024/11/21', url: 'https://docs.google.com/document/d/1A7gUZfBoFCOIG05gK5n4e9aCaAArmaLH/preview', description: '請假申請與簽核步驟。', category: 'dept1' },
  { id: 'flow_d2_1', title: '投資人投資粒子流程表', date: '2025/07/16', url: 'https://docs.google.com/document/d/1osLdqtDlozKHgtQSlnJ54p17yiqXWH277jE3g6AJ6oY/preview', description: '投資人入資標準服務流程。', category: 'dept2' },
  { id: 'flow_d2_2', title: '投資人退資粒子流程表', date: '2025/07/31', url: 'https://docs.google.com/document/d/1G7ydw_fUQVtqOnERpv6YGF0BVr5QSHyLP-IfpYSngTw/preview', description: '投資人退資申請流程。', category: 'dept2' },
  { id: 'flow_d3_1', title: '採購單流程表', date: '2024/09/24', url: 'https://docs.google.com/document/d/1OfZqaBb1Qtf70nP294GgAm9wlz_2TKmQ28MubXyvwQo/preview', description: '採購申請與驗收付款。', category: 'dept3' },
  { id: 'flow_d3_2', title: '客戶清償流程表', date: '2024/08/29', url: 'https://docs.google.com/document/d/1Aj0ywbHU1yEmETEThFRCw0g7vwA8ZMUpOwzUmr-uB3U/preview', description: '客戶結清債務與清償證明。', category: 'dept3' },
  { id: 'flow_d3_3', title: '財務計畫粒子流程表', date: '2024/09/12', url: 'https://docs.google.com/document/d/14g1tBbm0y3CcPher_leU-l4vKxGqha_LMLt4bT0H3ps/preview', description: '預算編列與資金分配。', category: 'dept3' },
  { id: 'flow_d3_4', title: '案件催收流程表', date: '2024/08/16', url: 'https://docs.google.com/document/d/18tiSDDb__ThxiY8Db8AjCAtOZPSKhcSFmDyVOxPmbxA/preview', description: '逾期案件催收處置。', category: 'dept3' },
  { id: 'flow_d4_1', title: '案件代償流程表', date: '2024/10/29', url: 'https://docs.google.com/document/d/1lfRdOaJCPXihBizer5SsMYin8Ia_yYmkiwK6NzjyHe8/preview', description: '代償案件申請審核。', category: 'dept4' },
  { id: 'flow_d4_2', title: '案件對保撥款流程表', date: '2024/11/14', url: 'https://docs.google.com/document/d/1W3SvKNV9c9oSKrg0gH_qbx5mEIkhlsOaBSLtOUNA8zE/preview', description: '簽約對保與撥款作業。', category: 'dept4' },
  { id: 'flow_d7_1', title: '合約簽立粒子流程表', date: '2025/04/10', url: 'https://docs.google.com/document/d/1h6lNL7Ndd3njY11bm7f6AT5NmN7244EFdUXOk73Zjo4/preview', description: '合約擬定與簽署步驟。', category: 'dept7' },
  { id: 'flow_d7_2', title: '發布審核粒子流程表', date: '2025/11/11', url: 'https://docs.google.com/document/d/1LxdbMT10tslZIKkA92RepntSr8qcAptatr5yUGjn1nU/preview', description: '對外發布內容審查。', category: 'dept7' },
  { id: 'flow_d7_3', title: '帳號異動粒子流程表', date: '2025/03/03', url: 'https://docs.google.com/document/d/1LlcuE1meUvzEJNTiKynlAh94YexcmKq0Aeru9EmQa_8/preview', description: '帳號新增、修改權限與停用之作業流程。', category: 'dept7' },
];

export const FORMS_DATA: DocItem[] = [
  { id: 'form_doc_1', title: '1. 結案標籤格式', date: '', url: 'https://docs.google.com/document/d/1xhSOS_syFtsDOGfFzAZPoCo3onUYi-dz/preview', description: '專案或案件結案歸檔時，文件夾脊背與封面的標準標籤格式範本。', category: 'docs' },
  { id: 'form_doc_2', title: '2. 融鎰多孔夾封面命名格式', date: '', url: 'https://docs.google.com/document/d/1D5a0yClbA4CP53BrWFvTgph4sEUj3jPK/preview', description: '統一規範多孔夾封面的命名規則與排版樣式。', category: 'docs' },
  { id: 'form_doc_3', title: '3. 一般多孔夾封面命名格式', date: '', url: 'https://docs.google.com/document/d/1GxWjYNoqOXVxo0j65Qe2ltqN6A1En_we/preview', description: '通用版多孔夾封面的標準命名與排版格式。', category: 'docs' },
  { id: 'form_doc_4', title: '4. 內頁標籤格式', date: '', url: 'https://docs.google.com/document/d/1kOWV7in-8fnjHCbjIYzd8hNUrabuN37S/preview', description: '文件內頁分類標籤的標準格式範本。', category: 'docs' },
  { id: 'form_doc_5', title: '5. 勾選式目錄格式', date: '', url: 'https://docs.google.com/document/d/12XtAcbalPwVwNUl6F95G0EKtbPbsrvHH/preview', description: '標準化的勾選式目錄表格，用於文件核對與索引。', category: 'docs' },
  { id: 'form_seal_1', title: '1. 印鑑刻製申請單', date: '', url: 'https://docs.google.com/document/d/1o1FYHaDyp0hg-e8sTuer0vdKAqvJdEGnQaTCatj1POE/preview', description: '申請新刻公司章、部門章或職務章的標準申請表格。', category: 'seals' },
  { id: 'form_seal_2', title: '2. 印鑑遺失/報銷申請單', date: '', url: 'https://docs.google.com/document/d/1f7aIZMYtX-S5ZNcJd5XoR8Z3NMtCFlm8/preview', description: '印鑑遺失申報或磨損報廢時使用的正式紀錄與審核單據。', category: 'seals' },
  { id: 'form_seal_3', title: '3. 用印申請CSW', date: '', url: 'https://docs.google.com/document/d/1aU1da1CnhxbQAO_BUCgWdaAZM029mVb9/preview', description: '符合CSW標準的用印申請文件，確保用印權限與文件內容經完整審核。', category: 'seals' },
  { id: 'form_fin_1', title: '1. 資金申請單', date: '', url: 'https://docs.google.com/document/d/1UdVNHe4b4dT9XJkyX0kUUT_OXnPFmacc/preview', description: '各部門申請專案資金、採購費用或日常支出的標準請款表格。', category: 'finance_form' },
  { id: 'form_hr_1', title: '1. 招聘需求單', date: '2026/01/22', url: 'https://docs.google.com/document/d/1owVrXFVtbZ-XoKJIlIkfmmYEzoTGyAgz/preview', description: '用人單位提出增補人力需求時，詳述職缺條件與工作內容的申請單。', category: 'hr' },
  { id: 'form_hr_2', title: '2. 溝通單', date: '', url: 'https://docs.google.com/document/d/1jwIEgdwQvwUYsjSUlEqRkOC8e0WynBUA/preview', description: '公司內部跨部門或上下級間正式書面溝通的標準格式。', category: 'hr' },
  { id: 'form_hr_3', title: '3. 遵從報告', date: '', url: 'https://docs.google.com/document/d/1ZD-A5xPpkrGIEP6oxuKGnYkjJkqCbpoJ/preview', description: '員工確認已閱讀並理解公司新發布政策或規章的簽署報告。', category: 'hr' },
  { id: 'form_hr_4', title: '4. 示知報告', date: '', url: 'https://docs.google.com/document/d/11R39D2Bd_5UPdnJxbSw7CHunIdsUnDWu/preview', description: '主動回報工作進度、異常狀況或潛在問題的標準報告格式。', category: 'hr' },
  { id: 'form_hr_5', title: '5. CSW', date: '', url: 'https://docs.google.com/document/d/1yM4C22M7ErtO0hwMLC9Nl9cky6HiCwYa/preview', description: '完成職員工作(Completed Staff Work)的標準提案格式，供主管決策使用。', category: 'hr' },
  { id: 'form_hr_6', title: '6. 職務說明', date: '', url: 'https://docs.google.com/document/d/1DeQfGr3CFfz9IIdu_VDDXdfDaGavtcj3/preview', description: '詳細記錄特定職位的職責範圍、績效指標與所需技能的說明文件。', category: 'hr' },
  { id: 'form_hr_7', title: '7. 職務移轉兩週工作測試', date: '', url: 'https://docs.google.com/document/d/19_ufwOIANpPWNdFjg4h6NWRE11IZtJvI/preview', description: '評估職務交接或輪調人員在適應期內工作表現的測試紀錄表。', category: 'hr' },
  { id: 'form_hr_8', title: '8. 加速員30天挑戰賽任務清單', date: '', url: 'https://docs.google.com/document/d/1r5un0pHsIkkKPgGKTX_0MEXC97vpg2Q4/preview', description: '新進加速員在首月需完成的各項學習任務與挑戰目標檢核表。', category: 'hr' },
  { id: 'form_hr_9', title: '9. 主管推薦函(通過試用期)', date: '', url: 'https://docs.google.com/document/d/1RCtF8JUVlgAAnYyPdgM_wios_xmQcQph734hH_MMFrY/preview', description: '主管評估新進員工試用期表現，建議予以正式任用的推薦文件。', category: 'hr' },
  { id: 'form_hr_10', title: '10. 職員晉升-主管推薦函', date: '', url: 'https://docs.google.com/document/d/1kF5A-z1UIBtMTJQcgFuHtiA9NlsbX32a/preview', description: '主管提名優秀部屬晉升職等時填寫的績效舉證與推薦理由書。', category: 'hr' },
  { id: 'form_hr_11', title: '11. 職員晉升-自我推薦函', date: '', url: 'https://docs.google.com/document/d/1oYX__cOc5ycyhrfLwP7KSwmvIpL2O8nx/preview', description: '員工主動爭取晉升機會，闡述個人貢獻與未來展望的自薦信。', category: 'hr' },
  { id: 'form_hr_12', title: '12. 部門主管-終止契約訪談表', date: '', url: 'https://docs.google.com/document/d/1su7ELrkeOIRr7S9QxzYS3v8597yPQCO4/preview', description: '主管與離職員工進行最後訪談的紀錄表，用於了解離職原因與交接狀況。', category: 'hr' },
  { id: 'form_hr_13', title: '13. 離職移轉專案及職位清單', date: '', url: 'https://docs.google.com/document/d/1cj7yBzIk1qcUvU4OOX9BbtLE85vc2fFJ/preview', description: '詳細列出離職員工負責的待辦專案、資產與權限的移轉清單。', category: 'hr' },
  { id: 'form_pr_1', title: '1. 活動紀錄素材需求表', date: '', url: 'https://docs.google.com/document/d/1pi3k1dCCAPDp-UzEy6wxnJXACH0Z8raU_aRrmxwNxu4/preview', description: '申請活動攝影、錄影或文案紀錄時，詳列需求細節的表格。', category: 'pr' },
  { id: 'form_pr_2', title: '2. 公關需求表', date: '', url: 'https://docs.google.com/document/d/1KLIjDbDxfOQljzTkPmpzD8Dh9vCBTDv9iQYzn8l39q4/preview', description: '各部門申請對外公關發布、媒體聯繫或品牌宣傳資源的需求單。', category: 'pr' },
  { id: 'form_mgmt_1', title: '1. 任命狀', date: '', url: 'https://docs.google.com/document/d/1uAj3EA2oU9mrsOFcWIbm2vzakTKt80rsxO1k2Jx5bkQ/preview', description: '正式發布人事任命、職務調動或晉升公告的標準文件格式。', category: 'mgmt' },
  { id: 'form_profit_1', title: '1. 顧問服務完成確認單', date: '', url: 'https://docs.google.com/document/d/1u3OXM2cAV829ZROE2y-wDK6s3X-V8PkL/preview', description: '顧問服務結束後，由客戶簽署確認服務內容已交付並滿意的單據。', category: 'profit' },
  { id: 'form_mgmt_2', title: '2. 衝突風險通報單-CSW', date: '2026/01/22', url: 'https://docs.google.com/document/d/1ZLX-0uvKyv5rBBX6INbmHPOOksK9G8X1/preview', description: '用於通報商務衝突風險與安全疑慮的標準表單。', category: 'mgmt' },
];
